### ISSUE TITLE
Movement Input Bug

### ISSUE THREAD

**Issue by joematrix77** [BenPyton/DungeonExample#1]
When you hit play on the Dungeon example v3.0 the character drifts around kind of like stick drift on a console controller the camera does as well. Thanks for the Plugin. This is on a fresh copy of the v3 plugin with new v3 example project.

**Comment by BenPyton** [comment]
Hi @joematrix77 

First, thank you to take your time reporting your issues.

I've downloaded a fresh copy of this example project and of the plugin v3.0 for UE 5.2 to test your issue and I have no drift with my controller.

Did you tried with another controller?\
What about using only keyboard+mouse? (no controller connected at all)

Maybe your controller has a little dirft, you should check if you can configure a dead zone in your controller's driver (because you could have this issue with other games too).

Also it is possible to configure a dead zone in the example project:
- In the content browser, go to `Blueprints` > `Player` > `Inputs`
- Open the `Input_Move` and the `Input_Camera` assets
- Add in each asset a `Modifier` and select `Dead Zone` in the drop down.

If that fixes your issue then I'll push this change in this repo.

Best regards.

**Comment by joematrix77** [comment]
This is with only mouse and keyboard, I added a third person character to visualize what's going on. Once I move forward the character gets stuck walking in place with no input from the mouse or keyboard. I am using UE 5.2.1. and no changes to the original files have been made. I will add a game pad to test later today.

**Comment by BenPyton** [comment]
Oh sorry I presumed you were using a controller since you talked about it... 😓

I don't have your issue neither with keyboard+mouse on my side.
What is your keyboard layout? The input I've set in the project are for an AZERTY keyboard.
Maybe you have something on your PC conflicting or doing something with one of the keys ZQSD?

You can isolate the key culprit by removing one by one the action mapping inside the asset:\
`Blueprints`>`Player`>`Inputs`>`InputContext_Default`

An then, you could maybe change the key to another one to see if your issue persists.
Let me know if you found the root cause of your issue, there is maybe something to do in the project to fix that.

**Comment by joematrix77** [comment]
Thanks for the speedy response, OK so I connected a controller and it did the same but after adding the dead zone it is somewhat functioning correctly now. The character skates with or without Root motion with the default ABP_Manny Blueprint. Thanks for the help!

**Comment by BenPyton** [comment]
Glad to hear that!
And does the dead zone without your controller connected fixed your issue with the keyboard too?
If so, maybe your keyboard doesn't send boolean values but scalar values of how much the keys are pressed?

**Comment by joematrix77** [comment]
> Glad to hear that! And does the dead zone without your controller connected fixed your issue with the keyboard too? If so, maybe your keyboard doesn't send boolean values but scalar values of how much the keys are pressed?

Yes it is working with keyboard and mouse, Thank you just realized I need to add a 3D blend space to stop the skating. Do you have a discord?

**Comment by BenPyton** [comment]
Glad to know you've resolved your issue!
So the problem was not with the inputs? Or are the dead zones mandatory to fix your issue?

>Do you have a discord?

I prefer to keep my discord for close firends only 😉

**Comment by joematrix77** [comment]
> Glad to know you've resolved your issue! So the problem was not with the inputs? Or are the dead zones mandatory to fix your issue?
> 
> > Do you have a discord?
> 
> I prefer to keep my discord for close friends only 😉

Dead Zones if I remove them the character starts walking in place. If you are open to doing some contract work let me know thanks!
